-- ============================================================================
-- Migration 202: Pillar Analysis and Risk Scenarios
-- ============================================================================
-- Adds comprehensive pillar-by-pillar narratives and worst-case analysis
-- for each product evaluation. Generated by Claude AI.
--
-- Author: Claude Opus 4.5
-- Date: 2026-02-01
-- ============================================================================

-- ============================================================================
-- 1. PILLAR NARRATIVES TABLE
-- ============================================================================
-- Stores AI-generated narrative summaries for each pillar per product
-- These explain WHY a product scored a certain way on each pillar
-- and provide security strategy recommendations

CREATE TABLE IF NOT EXISTS product_pillar_narratives (
    id BIGSERIAL PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    pillar CHAR(1) NOT NULL CHECK (pillar IN ('S', 'A', 'F', 'E')),

    -- AI-generated narrative content (in English)
    narrative_summary TEXT NOT NULL,          -- 3-5 sentence summary of pillar performance
    key_strengths TEXT,                       -- What the product does well in this pillar
    key_weaknesses TEXT,                      -- Areas for improvement
    security_strategy TEXT NOT NULL,          -- Recommended security strategy for using this product

    -- Worst-case scenario analysis
    worst_case_scenario TEXT NOT NULL,        -- What could go wrong if vulnerabilities exploited
    risk_level VARCHAR(20) DEFAULT 'medium' CHECK (risk_level IN ('low', 'medium', 'high', 'critical')),
    mitigation_advice TEXT,                   -- How to mitigate the risks

    -- Score context
    pillar_score DECIMAL(5,2),                -- Snapshot of score when narrative generated
    evaluated_norms_count INTEGER DEFAULT 0,  -- How many norms were evaluated for this pillar
    failed_norms_count INTEGER DEFAULT 0,     -- How many norms failed

    -- Metadata
    ai_model VARCHAR(50) DEFAULT 'claude-opus',
    generated_at TIMESTAMPTZ DEFAULT NOW(),
    last_updated_at TIMESTAMPTZ DEFAULT NOW(),

    UNIQUE(product_id, pillar)
);

-- Index for fast lookups
CREATE INDEX IF NOT EXISTS idx_pillar_narratives_product ON product_pillar_narratives(product_id);
CREATE INDEX IF NOT EXISTS idx_pillar_narratives_pillar ON product_pillar_narratives(pillar);
CREATE INDEX IF NOT EXISTS idx_pillar_narratives_risk ON product_pillar_narratives(risk_level);

-- ============================================================================
-- 2. ENHANCED EVALUATION JUSTIFICATIONS
-- ============================================================================
-- Increase justification storage capacity and add structured fields

-- First, check if column exists and alter if needed
DO $$
BEGIN
    -- Add or modify why_this_result column to TEXT (unlimited)
    IF EXISTS (SELECT 1 FROM information_schema.columns
               WHERE table_name = 'evaluations' AND column_name = 'why_this_result') THEN
        -- Column exists, ensure it's TEXT (not VARCHAR with limit)
        ALTER TABLE evaluations ALTER COLUMN why_this_result TYPE TEXT;
    ELSE
        -- Column doesn't exist, add it
        ALTER TABLE evaluations ADD COLUMN why_this_result TEXT;
    END IF;

    -- Add detailed justification field for longer explanations
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_name = 'evaluations' AND column_name = 'detailed_justification') THEN
        ALTER TABLE evaluations ADD COLUMN detailed_justification TEXT;
    END IF;

    -- Add evidence sources field (for citations and documentation links)
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_name = 'evaluations' AND column_name = 'evidence_sources') THEN
        ALTER TABLE evaluations ADD COLUMN evidence_sources JSONB DEFAULT '[]';
    END IF;

    -- Add per-norm risk impact field
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_name = 'evaluations' AND column_name = 'risk_impact') THEN
        ALTER TABLE evaluations ADD COLUMN risk_impact VARCHAR(20) DEFAULT 'low'
            CHECK (risk_impact IN ('negligible', 'low', 'medium', 'high', 'critical'));
    END IF;
END $$;

-- ============================================================================
-- 3. PRODUCT RISK ANALYSIS TABLE
-- ============================================================================
-- Stores overall product risk analysis combining all pillars

CREATE TABLE IF NOT EXISTS product_risk_analysis (
    id BIGSERIAL PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,

    -- Overall risk assessment
    overall_risk_level VARCHAR(20) DEFAULT 'medium' CHECK (overall_risk_level IN ('low', 'medium', 'high', 'critical')),
    overall_risk_narrative TEXT NOT NULL,     -- Summary of all risks across pillars

    -- Combined worst-case scenario
    combined_worst_case TEXT NOT NULL,        -- What happens if multiple vulnerabilities exploited
    attack_vectors JSONB DEFAULT '[]',        -- List of potential attack vectors

    -- Mitigation summary
    priority_mitigations JSONB DEFAULT '[]',  -- Ordered list of priority actions
    estimated_improvement JSONB DEFAULT '{}', -- Estimated score improvement per mitigation

    -- Context
    total_critical_norms_failed INTEGER DEFAULT 0,
    total_high_risk_norms INTEGER DEFAULT 0,

    -- Metadata
    ai_model VARCHAR(50) DEFAULT 'claude-opus',
    generated_at TIMESTAMPTZ DEFAULT NOW(),
    last_updated_at TIMESTAMPTZ DEFAULT NOW(),

    UNIQUE(product_id)
);

CREATE INDEX IF NOT EXISTS idx_risk_analysis_product ON product_risk_analysis(product_id);
CREATE INDEX IF NOT EXISTS idx_risk_analysis_level ON product_risk_analysis(overall_risk_level);

-- ============================================================================
-- 4. APPLICABILITY JUSTIFICATIONS TABLE
-- ============================================================================
-- Stores why each norm is or isn't applicable to a product type

CREATE TABLE IF NOT EXISTS norm_applicability_justifications (
    id SERIAL PRIMARY KEY,
    product_type VARCHAR(50) NOT NULL,
    norm_id INTEGER NOT NULL REFERENCES norms(id) ON DELETE CASCADE,

    is_applicable BOOLEAN NOT NULL,
    justification TEXT NOT NULL,              -- Why this norm applies/doesn't apply
    applicability_score DECIMAL(3,2),         -- 0-1 confidence in applicability decision

    -- Context
    product_characteristics JSONB DEFAULT '{}', -- What product features affect applicability

    -- Metadata
    ai_model VARCHAR(50) DEFAULT 'claude-opus',
    generated_at TIMESTAMPTZ DEFAULT NOW(),

    UNIQUE(product_type, norm_id)
);

CREATE INDEX IF NOT EXISTS idx_applicability_type ON norm_applicability_justifications(product_type);
CREATE INDEX IF NOT EXISTS idx_applicability_norm ON norm_applicability_justifications(norm_id);

-- ============================================================================
-- 5. FUNCTION: Generate Pillar Narratives After Evaluation
-- ============================================================================

CREATE OR REPLACE FUNCTION generate_pillar_narrative_placeholder(
    p_product_id BIGINT,
    p_pillar CHAR(1)
) RETURNS VOID AS $$
DECLARE
    v_pillar_score DECIMAL(5,2);
    v_evaluated_count INTEGER;
    v_failed_count INTEGER;
    v_pillar_name VARCHAR(20);
BEGIN
    -- Get pillar name
    v_pillar_name := CASE p_pillar
        WHEN 'S' THEN 'Security'
        WHEN 'A' THEN 'Adversity'
        WHEN 'F' THEN 'Fidelity'
        WHEN 'E' THEN 'Efficiency'
    END;

    -- Get current pillar score
    SELECT
        CASE p_pillar
            WHEN 'S' THEN score_s
            WHEN 'A' THEN score_a
            WHEN 'F' THEN score_f
            WHEN 'E' THEN score_e
        END
    INTO v_pillar_score
    FROM safe_scoring_results
    WHERE product_id = p_product_id
    ORDER BY calculated_at DESC
    LIMIT 1;

    -- Count evaluations for this pillar
    SELECT
        COUNT(*),
        COUNT(*) FILTER (WHERE e.result IN ('NO', 'N'))
    INTO v_evaluated_count, v_failed_count
    FROM evaluations e
    JOIN norms n ON e.norm_id = n.id
    WHERE e.product_id = p_product_id
      AND n.pillar = p_pillar;

    -- Insert or update placeholder (to be filled by AI later)
    INSERT INTO product_pillar_narratives (
        product_id,
        pillar,
        narrative_summary,
        security_strategy,
        worst_case_scenario,
        risk_level,
        pillar_score,
        evaluated_norms_count,
        failed_norms_count
    ) VALUES (
        p_product_id,
        p_pillar,
        'Pending AI analysis for ' || v_pillar_name || ' pillar.',
        'Pending AI-generated security strategy.',
        'Pending AI-generated worst-case scenario analysis.',
        CASE
            WHEN v_pillar_score >= 80 THEN 'low'
            WHEN v_pillar_score >= 60 THEN 'medium'
            WHEN v_pillar_score >= 40 THEN 'high'
            ELSE 'critical'
        END,
        v_pillar_score,
        v_evaluated_count,
        v_failed_count
    )
    ON CONFLICT (product_id, pillar) DO UPDATE SET
        pillar_score = EXCLUDED.pillar_score,
        evaluated_norms_count = EXCLUDED.evaluated_norms_count,
        failed_norms_count = EXCLUDED.failed_norms_count,
        risk_level = EXCLUDED.risk_level,
        last_updated_at = NOW();
END;
$$ LANGUAGE plpgsql;

-- ============================================================================
-- 6. TRIGGER: Auto-create placeholder narratives after score calculation
-- ============================================================================

CREATE OR REPLACE FUNCTION trigger_create_narrative_placeholders()
RETURNS TRIGGER AS $$
BEGIN
    -- Create placeholders for all pillars
    PERFORM generate_pillar_narrative_placeholder(NEW.product_id, 'S');
    PERFORM generate_pillar_narrative_placeholder(NEW.product_id, 'A');
    PERFORM generate_pillar_narrative_placeholder(NEW.product_id, 'F');
    PERFORM generate_pillar_narrative_placeholder(NEW.product_id, 'E');
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Drop existing trigger if exists
DROP TRIGGER IF EXISTS trg_create_narrative_placeholders ON safe_scoring_results;

-- Create trigger
CREATE TRIGGER trg_create_narrative_placeholders
    AFTER INSERT OR UPDATE ON safe_scoring_results
    FOR EACH ROW
    EXECUTE FUNCTION trigger_create_narrative_placeholders();

-- ============================================================================
-- 7. VIEW: Complete Product Analysis
-- ============================================================================

CREATE OR REPLACE VIEW v_product_complete_analysis AS
SELECT
    p.id AS product_id,
    p.name AS product_name,
    p.slug,
    p.type AS product_type,

    -- Scores
    ssr.note_finale AS total_score,
    ssr.score_s,
    ssr.score_a,
    ssr.score_f,
    ssr.score_e,

    -- Pillar narratives (JSON aggregation)
    (
        SELECT jsonb_object_agg(
            pillar,
            jsonb_build_object(
                'narrative', narrative_summary,
                'strengths', key_strengths,
                'weaknesses', key_weaknesses,
                'strategy', security_strategy,
                'worstCase', worst_case_scenario,
                'riskLevel', risk_level,
                'mitigation', mitigation_advice,
                'score', pillar_score,
                'evaluatedCount', evaluated_norms_count,
                'failedCount', failed_norms_count
            )
        )
        FROM product_pillar_narratives ppn
        WHERE ppn.product_id = p.id
    ) AS pillar_analysis,

    -- Overall risk
    pra.overall_risk_level,
    pra.overall_risk_narrative,
    pra.combined_worst_case,
    pra.attack_vectors,
    pra.priority_mitigations,

    -- Evaluation counts
    ssr.yes_count,
    ssr.no_count,
    ssr.na_count,
    ssr.tbd_count,
    ssr.calculated_at

FROM products p
LEFT JOIN safe_scoring_results ssr ON p.id = ssr.product_id
    AND ssr.calculated_at = (
        SELECT MAX(calculated_at)
        FROM safe_scoring_results
        WHERE product_id = p.id
    )
LEFT JOIN product_risk_analysis pra ON p.id = pra.product_id;

-- ============================================================================
-- 8. GRANT PERMISSIONS
-- ============================================================================

-- Enable RLS
ALTER TABLE product_pillar_narratives ENABLE ROW LEVEL SECURITY;
ALTER TABLE product_risk_analysis ENABLE ROW LEVEL SECURITY;
ALTER TABLE norm_applicability_justifications ENABLE ROW LEVEL SECURITY;

-- Public read access (narratives are public content)
CREATE POLICY "Public can read pillar narratives"
    ON product_pillar_narratives FOR SELECT
    USING (true);

CREATE POLICY "Public can read risk analysis"
    ON product_risk_analysis FOR SELECT
    USING (true);

CREATE POLICY "Public can read applicability justifications"
    ON norm_applicability_justifications FOR SELECT
    USING (true);

-- Service role can write
CREATE POLICY "Service role can write pillar narratives"
    ON product_pillar_narratives FOR ALL
    USING (auth.role() = 'service_role');

CREATE POLICY "Service role can write risk analysis"
    ON product_risk_analysis FOR ALL
    USING (auth.role() = 'service_role');

CREATE POLICY "Service role can write applicability justifications"
    ON norm_applicability_justifications FOR ALL
    USING (auth.role() = 'service_role');

-- ============================================================================
-- 9. COMMENTS
-- ============================================================================

COMMENT ON TABLE product_pillar_narratives IS
    'AI-generated narrative summaries per pillar for each product, including security strategies and worst-case scenarios';

COMMENT ON TABLE product_risk_analysis IS
    'Combined risk analysis across all pillars for each product';

COMMENT ON TABLE norm_applicability_justifications IS
    'Justifications for why each norm is applicable or not to each product type';

COMMENT ON VIEW v_product_complete_analysis IS
    'Complete product analysis view combining scores, narratives, and risk analysis';

-- ============================================================================
-- END OF MIGRATION
-- ============================================================================
