-- Product Pillar Strategic Analyses
-- Strategic conclusions per product per pillar (Security, Adversity, Fidelity, Ecosystem)
-- Generated by Claude Opus for display on frontend

CREATE TABLE IF NOT EXISTS product_pillar_analyses (
    id BIGSERIAL PRIMARY KEY,
    product_id INTEGER NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    pillar VARCHAR(1) NOT NULL CHECK (pillar IN ('S', 'A', 'F', 'E')),

    -- Scores
    pillar_score NUMERIC(5,2) CHECK (pillar_score >= 0 AND pillar_score <= 100),
    confidence_score NUMERIC(3,2) CHECK (confidence_score >= 0 AND confidence_score <= 1),

    -- Strategic Analysis (in English for universal understanding)
    strategic_conclusion TEXT NOT NULL,
    key_strengths TEXT[],
    key_weaknesses TEXT[],
    critical_risks TEXT[],
    recommendations TEXT[],

    -- Context
    evaluated_norms_count INTEGER DEFAULT 0,
    passed_norms_count INTEGER DEFAULT 0,
    failed_norms_count INTEGER DEFAULT 0,
    tbd_norms_count INTEGER DEFAULT 0,

    -- Community voting integration
    community_vote_count INTEGER DEFAULT 0,
    community_avg_rating NUMERIC(3,2),

    -- Metadata
    generated_by VARCHAR(100) DEFAULT 'claude_opus_4.5_strategic',
    generated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    -- Unique constraint: one analysis per product per pillar
    UNIQUE(product_id, pillar)
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_product_pillar_analyses_product ON product_pillar_analyses(product_id);
CREATE INDEX IF NOT EXISTS idx_product_pillar_analyses_pillar ON product_pillar_analyses(pillar);
CREATE INDEX IF NOT EXISTS idx_product_pillar_analyses_score ON product_pillar_analyses(pillar_score DESC);

-- RLS Policies (read-only for all, write only for authenticated)
ALTER TABLE product_pillar_analyses ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can view product pillar analyses"
    ON product_pillar_analyses FOR SELECT
    USING (true);

CREATE POLICY "Authenticated users can insert product pillar analyses"
    ON product_pillar_analyses FOR INSERT
    WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Authenticated users can update product pillar analyses"
    ON product_pillar_analyses FOR UPDATE
    USING (auth.role() = 'authenticated');

-- Function to recalculate pillar score based on evaluations
CREATE OR REPLACE FUNCTION calculate_pillar_score(
    p_product_id INTEGER,
    p_pillar VARCHAR(1)
)
RETURNS TABLE (
    score NUMERIC(5,2),
    total_norms INTEGER,
    passed INTEGER,
    failed INTEGER,
    tbd INTEGER
) AS $$
BEGIN
    RETURN QUERY
    SELECT
        ROUND(
            (COUNT(*) FILTER (WHERE e.result = 'YES') * 100.0) /
            NULLIF(COUNT(*) FILTER (WHERE e.result IN ('YES', 'NO')), 0),
            2
        ) as score,
        COUNT(*)::INTEGER as total_norms,
        COUNT(*) FILTER (WHERE e.result = 'YES')::INTEGER as passed,
        COUNT(*) FILTER (WHERE e.result = 'NO')::INTEGER as failed,
        COUNT(*) FILTER (WHERE e.result = 'TBD')::INTEGER as tbd
    FROM evaluations e
    JOIN norms n ON e.norm_id = n.id
    WHERE e.product_id = p_product_id
      AND n.pillar = p_pillar
      AND e.result IN ('YES', 'NO', 'TBD');
END;
$$ LANGUAGE plpgsql STABLE;

-- Trigger to update updated_at
CREATE OR REPLACE FUNCTION update_product_pillar_analyses_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER product_pillar_analyses_updated_at
    BEFORE UPDATE ON product_pillar_analyses
    FOR EACH ROW
    EXECUTE FUNCTION update_product_pillar_analyses_updated_at();

COMMENT ON TABLE product_pillar_analyses IS 'Strategic analyses per product per SAFE pillar (Security, Adversity, Fidelity, Ecosystem). Generated by Claude Opus to provide nuanced, strategic conclusions for users.';
COMMENT ON COLUMN product_pillar_analyses.strategic_conclusion IS 'Main strategic conclusion for this pillar - comprehensive analysis of the product security/adversity/fidelity/ecosystem posture';
COMMENT ON COLUMN product_pillar_analyses.key_strengths IS 'Array of key strengths identified for this pillar';
COMMENT ON COLUMN product_pillar_analyses.key_weaknesses IS 'Array of key weaknesses identified for this pillar';
COMMENT ON COLUMN product_pillar_analyses.critical_risks IS 'Array of critical risks that users should be aware of';
COMMENT ON COLUMN product_pillar_analyses.recommendations IS 'Array of strategic recommendations for using this product';
