-- Migration: Create white-label branding tables
-- Purpose: Store Enterprise customer branding configurations for PDF reports
-- Run this in Supabase SQL Editor

-- User branding table (white-label settings)
CREATE TABLE IF NOT EXISTS user_branding (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  company_name TEXT,
  logo_url TEXT,
  logo_base64 TEXT, -- Base64 encoded logo for PDF embedding
  primary_color TEXT DEFAULT '#3B82F6',
  secondary_color TEXT DEFAULT '#8B5CF6',
  header_color TEXT DEFAULT '#1F2937',
  header_text TEXT DEFAULT 'Security Assessment Report',
  footer_text TEXT DEFAULT 'Generated by SafeScoring.io',
  website_url TEXT,
  show_safescoring BOOLEAN DEFAULT TRUE,
  custom_css TEXT, -- For HTML reports
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id)
);

-- Report generation logs (analytics)
CREATE TABLE IF NOT EXISTS report_generations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  report_type TEXT NOT NULL, -- 'setup', 'comparison', 'product'
  branding_used BOOLEAN DEFAULT FALSE,
  setup_id UUID, -- Reference if type is setup
  product_slugs TEXT[], -- Products included
  format TEXT DEFAULT 'pdf', -- 'pdf', 'html'
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_user_branding_user ON user_branding(user_id);
CREATE INDEX IF NOT EXISTS idx_report_generations_user ON report_generations(user_id);
CREATE INDEX IF NOT EXISTS idx_report_generations_date ON report_generations(created_at);
CREATE INDEX IF NOT EXISTS idx_report_generations_type ON report_generations(report_type);

-- Row Level Security
ALTER TABLE user_branding ENABLE ROW LEVEL SECURITY;
ALTER TABLE report_generations ENABLE ROW LEVEL SECURITY;

-- Users can only access their own branding
CREATE POLICY "Users can view their branding" ON user_branding
  FOR SELECT USING (user_id = auth.uid());

CREATE POLICY "Users can update their branding" ON user_branding
  FOR ALL USING (user_id = auth.uid());

-- Users can only see their own report logs
CREATE POLICY "Users can view their report logs" ON report_generations
  FOR SELECT USING (user_id = auth.uid());

CREATE POLICY "Users can create report logs" ON report_generations
  FOR INSERT WITH CHECK (user_id = auth.uid());

-- Service role full access
CREATE POLICY "Service role full access branding" ON user_branding
  FOR ALL USING (auth.role() = 'service_role');

CREATE POLICY "Service role full access report_generations" ON report_generations
  FOR ALL USING (auth.role() = 'service_role');

-- Update timestamp trigger
CREATE TRIGGER update_user_branding_updated_at
  BEFORE UPDATE ON user_branding
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- Add column to user_preferences if it doesn't exist (for backward compatibility)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'user_preferences'
    AND column_name = 'white_label_branding'
  ) THEN
    ALTER TABLE user_preferences ADD COLUMN white_label_branding JSONB;
  END IF;
END $$;

-- Comments
COMMENT ON TABLE user_branding IS 'Enterprise white-label branding configurations for PDF reports';
COMMENT ON TABLE report_generations IS 'Analytics log of generated reports';
COMMENT ON COLUMN user_branding.logo_base64 IS 'Base64 encoded logo image for direct PDF embedding';
COMMENT ON COLUMN user_branding.show_safescoring IS 'Whether to show "Powered by SafeScoring" in reports';
