#!/usr/bin/env python3
"""
Script de configuration des tables Supabase pour SafeScoring
Crée automatiquement les tables nécessaires via l'API SQL
"""

import os
import json
import requests
from datetime import datetime

# Configuration
SUPABASE_URL = "https://ajdncttomdqojlozxjxu.supabase.co"
SUPABASE_SERVICE_KEY = "REVOKED_ROTATE_ON_DASHBOARD"

class SupabaseSetup:
    """Configuration des tables Supabase"""
    
    def __init__(self, url, key):
        self.url = url
        self.key = key
        self.headers = {
            'apikey': key,
            'Authorization': f'Bearer {key}',
            'Content-Type': 'application/json',
            'Prefer': 'return=minimal'
        }
        self.rpc_headers = {
            'apikey': key,
            'Authorization': f'Bearer {key}',
            'Content-Type': 'application/json'
        }
    
    def execute_sql(self, sql_query):
        """Exécute une requête SQL via l'API RPC"""
        try:
            response = requests.post(
                f"{self.url}/rest/v1/rpc/exec",
                headers=self.rpc_headers,
                json={"query": sql_query}
            )
            
            if response.status_code == 200:
                print(f"✅ SQL exécuté avec succès")
                return True
            else:
                print(f"❌ Erreur SQL: {response.status_code} - {response.text}")
                return False
                
        except Exception as e:
            print(f"❌ Exception SQL: {e}")
            return False
    
    def create_products_table(self):
        """Crée la table products"""
        print("🔧 Création de la table 'products'...")
        
        sql = """
        CREATE TABLE IF NOT EXISTS public.products (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name TEXT NOT NULL,
            description TEXT,
            url TEXT,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
            last_security_scan TIMESTAMP WITH TIME ZONE,
            risk_score INTEGER DEFAULT 0,
            security_status TEXT DEFAULT 'pending',
            updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
        );
        
        -- Activer RLS (Row Level Security)
        ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
        
        -- Créer une politique pour permettre les opérations
        CREATE POLICY "Enable all operations for users" ON public.products
            FOR ALL USING (true) WITH CHECK (true);
        
        -- Créer un index pour améliorer les performances
        CREATE INDEX IF NOT EXISTS idx_products_security_status ON public.products(security_status);
        CREATE INDEX IF NOT EXISTS idx_products_last_scan ON public.products(last_security_scan);
        """
        
        return self.execute_sql(sql)
    
    def create_security_evaluations_table(self):
        """Crée la table security_evaluations"""
        print("🔧 Création de la table 'security_evaluations'...")
        
        sql = """
        CREATE TABLE IF NOT EXISTS public.security_evaluations (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
            ai_analysis JSONB,
            risk_score INTEGER,
            vulnerabilities TEXT[],
            recommendations TEXT[],
            created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
            analysis_model TEXT
        );
        
        -- Activer RLS
        ALTER TABLE public.security_evaluations ENABLE ROW LEVEL SECURITY;
        
        -- Politique pour permettre les opérations
        CREATE POLICY "Enable all operations for users" ON public.security_evaluations
            FOR ALL USING (true) WITH CHECK (true);
        
        -- Index
        CREATE INDEX IF NOT EXISTS idx_evaluations_product_id ON public.security_evaluations(product_id);
        CREATE INDEX IF NOT EXISTS idx_evaluations_created_at ON public.security_evaluations(created_at);
        """
        
        return self.execute_sql(sql)
    
    def create_automation_logs_table(self):
        """Crée la table automation_logs"""
        print("🔧 Création de la table 'automation_logs'...")
        
        sql = """
        CREATE TABLE IF NOT EXISTS public.automation_logs (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            run_type TEXT NOT NULL,
            products_processed INTEGER DEFAULT 0,
            products_updated INTEGER DEFAULT 0,
            vulnerabilities_found INTEGER DEFAULT 0,
            errors JSONB,
            started_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
            completed_at TIMESTAMP WITH TIME ZONE,
            duration_seconds INTEGER
        );
        
        -- Activer RLS
        ALTER TABLE public.automation_logs ENABLE ROW LEVEL SECURITY;
        
        -- Politique
        CREATE POLICY "Enable all operations for users" ON public.automation_logs
            FOR ALL USING (true) WITH CHECK (true);
        
        -- Index
        CREATE INDEX IF NOT EXISTS idx_logs_started_at ON public.automation_logs(started_at);
        CREATE INDEX IF NOT EXISTS idx_logs_run_type ON public.automation_logs(run_type);
        """
        
        return self.execute_sql(sql)
    
    def create_security_alerts_table(self):
        """Crée la table security_alerts"""
        print("🔧 Création de la table 'security_alerts'...")
        
        sql = """
        CREATE TABLE IF NOT EXISTS public.security_alerts (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
            alert_type TEXT NOT NULL,
            severity TEXT NOT NULL,
            title TEXT NOT NULL,
            description TEXT,
            cve_id TEXT,
            recommendation TEXT,
            status TEXT DEFAULT 'open',
            created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
            resolved_at TIMESTAMP WITH TIME ZONE
        );
        
        -- Activer RLS
        ALTER TABLE public.security_alerts ENABLE ROW LEVEL SECURITY;
        
        -- Politique
        CREATE POLICY "Enable all operations for users" ON public.security_alerts
            FOR ALL USING (true) WITH CHECK (true);
        
        -- Index
        CREATE INDEX IF NOT EXISTS idx_alerts_product_id ON public.security_alerts(product_id);
        CREATE INDEX IF NOT EXISTS idx_alerts_status ON public.security_alerts(status);
        CREATE INDEX IF NOT EXISTS idx_alerts_severity ON public.security_alerts(severity);
        """
        
        return self.execute_sql(sql)
    
    def test_tables(self):
        """Test si les tables existent et sont accessibles"""
        print("\n🧪 Test des tables...")
        
        tables = ['products', 'security_evaluations', 'automation_logs', 'security_alerts']
        
        for table in tables:
            try:
                response = requests.get(
                    f"{self.url}/rest/v1/{table}?select=count&limit=1",
                    headers=self.headers
                )
                
                if response.status_code == 200:
                    print(f"✅ Table '{table}' accessible")
                else:
                    print(f"❌ Table '{table}' inaccessible: {response.status_code}")
                    return False
                    
            except Exception as e:
                print(f"❌ Erreur test table '{table}': {e}")
                return False
        
        return True
    
    def setup_all_tables(self):
        """Configure toutes les tables nécessaires"""
        print("🚀 Configuration des tables Supabase pour SafeScoring")
        print("=" * 50)
        
        success = True
        
        # Créer chaque table
        success &= self.create_products_table()
        success &= self.create_security_evaluations_table()
        success &= self.create_automation_logs_table()
        success &= self.create_security_alerts_table()
        
        if success:
            print("\n✅ Toutes les tables ont été créées avec succès!")
            
            # Tester les tables
            if self.test_tables():
                print("\n🎉 Configuration terminée! Les tables sont prêtes à utiliser.")
                print("\n📝 Prochaine étape:")
                print("   Lancez 'python supabase_ai_demo.py' pour tester l'automatisation")
            else:
                print("\n⚠️  Tables créées mais erreur lors du test")
        else:
            print("\n❌ Erreur lors de la création des tables")
            print("Vérifiez vos permissions sur Supabase")
        
        return success

def main():
    """Fonction principale"""
    setup = SupabaseSetup(SUPABASE_URL, SUPABASE_SERVICE_KEY)
    setup.setup_all_tables()

if __name__ == "__main__":
    main()
