import { NextResponse } from "next/server";
import { auth } from "@/libs/auth";
import { supabase, isSupabaseConfigured } from "@/libs/supabase";
import { checkUnifiedAccess, getPlanLimits } from "@/libs/access";
import { validateRequestOrigin } from "@/libs/security";

/**
 * White-Label Reports API
 *
 * Enterprise feature for generating branded PDF reports.
 * Key revenue driver: enterprises pay for custom branding.
 *
 * GET - Get user's branding settings
 * POST - Update branding or generate report
 * PUT - Generate report data for client-side PDF generation
 */

// Maximum logo size (500KB base64)
const MAX_LOGO_SIZE = 500 * 1024;

// Default SafeScoring branding
const DEFAULT_BRANDING = {
  companyName: "SafeScoring",
  logoUrl: null,
  primaryColor: "#6366f1", // Indigo
  secondaryColor: "#10b981", // Emerald
  headerText: "Security Assessment Report",
  footerText: "Generated by SafeScoring.io",
  showSafeScoring: true,
  customCss: null,
};

// GET - Get user's branding settings
export async function GET(request) {
  const session = await auth();

  if (!session?.user) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  // Check if user has white-label access
  const access = await checkUnifiedAccess({ userId: session.user.id });
  const limits = getPlanLimits(access.plan);

  if (!limits.whiteLabel) {
    return NextResponse.json({
      branding: DEFAULT_BRANDING,
      isCustom: false,
      upgrade: true,
      message: "White-label branding requires Enterprise plan",
    });
  }

  if (!isSupabaseConfigured()) {
    return NextResponse.json({ error: "Service unavailable" }, { status: 503 });
  }

  try {
    // Get user's custom branding
    const { data: branding } = await supabase
      .from("user_branding")
      .select("*")
      .eq("user_id", session.user.id)
      .single();

    return NextResponse.json({
      branding: branding || DEFAULT_BRANDING,
      isCustom: !!branding,
    });
  } catch (error) {
    console.error("Error fetching branding:", error);
    return NextResponse.json({
      branding: DEFAULT_BRANDING,
      isCustom: false,
    });
  }
}

// POST - Generate report or update branding
export async function POST(request) {
  // CSRF protection for state-changing requests
  const originCheck = validateRequestOrigin(request);
  if (!originCheck.valid) {
    console.warn("[SECURITY] CSRF attempt blocked on white-label:", originCheck.reason);
    return NextResponse.json({ error: "Invalid request origin" }, { status: 403 });
  }

  const session = await auth();

  if (!session?.user) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  // Check access
  const access = await checkUnifiedAccess({ userId: session.user.id });
  const limits = getPlanLimits(access.plan);

  if (!limits.whiteLabel) {
    return NextResponse.json(
      { error: "White-label reports require Enterprise plan", upgrade: true },
      { status: 403 }
    );
  }

  if (!isSupabaseConfigured()) {
    return NextResponse.json({ error: "Service unavailable" }, { status: 503 });
  }

  try {
    const body = await request.json();
    const { action } = body;

    switch (action) {
      case "updateBranding": {
        const { branding } = body;

        if (!branding) {
          return NextResponse.json(
            { error: "Branding settings required" },
            { status: 400 }
          );
        }

        // Validate branding
        const validBranding = {
          company_name: branding.companyName?.substring(0, 100),
          logo_url: branding.logoUrl?.substring(0, 500),
          primary_color: isValidColor(branding.primaryColor) ? branding.primaryColor : null,
          secondary_color: isValidColor(branding.secondaryColor) ? branding.secondaryColor : null,
          header_text: branding.headerText?.substring(0, 200),
          footer_text: branding.footerText?.substring(0, 500),
          show_safescoring: branding.showSafeScoring !== false,
          custom_css: branding.customCss?.substring(0, 5000),
        };

        // Upsert branding
        const { data, error } = await supabase
          .from("user_branding")
          .upsert({
            user_id: session.user.id,
            ...validBranding,
            updated_at: new Date().toISOString(),
          }, { onConflict: "user_id" })
          .select()
          .single();

        if (error) throw error;

        return NextResponse.json({
          branding: transformBranding(data),
          message: "Branding updated successfully",
        });
      }

      case "generateReport": {
        const { productSlugs, setupId, format = "pdf", includeDetails = true } = body;

        if (!productSlugs?.length && !setupId) {
          return NextResponse.json(
            { error: "Product slugs or setup ID required" },
            { status: 400 }
          );
        }

        // Get branding
        const { data: brandingData } = await supabase
          .from("user_branding")
          .select("*")
          .eq("user_id", session.user.id)
          .single();

        const branding = brandingData ? transformBranding(brandingData) : DEFAULT_BRANDING;

        // Get products
        let products = [];

        if (setupId) {
          // Get setup products
          const { data: setup } = await supabase
            .from("user_setups")
            .select("products")
            .eq("id", setupId)
            .eq("user_id", session.user.id)
            .single();

          if (setup?.products) {
            const slugs = setup.products.map(p => p.slug || p.productSlug);
            const { data } = await supabase
              .from("products")
              .select(`
                id, name, slug, url,
                safe_scoring_results (
                  note_finale, score_s, score_a, score_f, score_e
                )
              `)
              .in("slug", slugs);
            products = data || [];
          }
        } else {
          // Get specific products
          const { data } = await supabase
            .from("products")
            .select(`
              id, name, slug, url,
              safe_scoring_results (
                note_finale, score_s, score_a, score_f, score_e
              )
            `)
            .in("slug", productSlugs);
          products = data || [];
        }

        if (products.length === 0) {
          return NextResponse.json(
            { error: "No products found" },
            { status: 404 }
          );
        }

        // Generate report content (HTML that will be converted to PDF)
        const reportHtml = generateReportHtml(products, branding, includeDetails);

        // For now, return HTML. In production, use a PDF library like puppeteer or pdfkit
        if (format === "html") {
          return new NextResponse(reportHtml, {
            headers: {
              "Content-Type": "text/html",
              "Content-Disposition": `attachment; filename="security-report-${Date.now()}.html"`,
            },
          });
        }

        // Return report data for client-side PDF generation
        return NextResponse.json({
          reportData: {
            html: reportHtml,
            branding,
            products: products.map(p => ({
              name: p.name,
              slug: p.slug,
              score: p.safe_scoring_results?.note_finale,
              pillarScores: {
                s: p.safe_scoring_results?.score_s,
                a: p.safe_scoring_results?.score_a,
                f: p.safe_scoring_results?.score_f,
                e: p.safe_scoring_results?.score_e,
              },
            })),
            generatedAt: new Date().toISOString(),
          },
          message: "Use the reportData to generate PDF client-side or call with format=html",
        });
      }

      case "previewBranding": {
        const { branding } = body;

        // Generate preview HTML with temporary branding
        const previewProducts = [
          {
            name: "Example Product",
            slug: "example",
            safe_scoring_results: {
              note_finale: 85.5,
              score_s: 88,
              score_a: 82,
              score_f: 86,
              score_e: 84,
            },
          },
        ];

        const previewHtml = generateReportHtml(
          previewProducts,
          { ...DEFAULT_BRANDING, ...branding },
          false
        );

        return NextResponse.json({ previewHtml });
      }

      default:
        return NextResponse.json({ error: "Unknown action" }, { status: 400 });
    }
  } catch (error) {
    console.error("Error in white-label POST:", error);
    return NextResponse.json({ error: "Internal server error" }, { status: 500 });
  }
}

// Validate hex color
function isValidColor(color) {
  if (!color) return false;
  return /^#[0-9A-Fa-f]{6}$/.test(color);
}

// Transform database branding to API format
function transformBranding(data) {
  return {
    companyName: data.company_name || DEFAULT_BRANDING.companyName,
    logoUrl: data.logo_url,
    primaryColor: data.primary_color || DEFAULT_BRANDING.primaryColor,
    secondaryColor: data.secondary_color || DEFAULT_BRANDING.secondaryColor,
    headerText: data.header_text || DEFAULT_BRANDING.headerText,
    footerText: data.footer_text || DEFAULT_BRANDING.footerText,
    showSafeScoring: data.show_safescoring !== false,
    customCss: data.custom_css,
  };
}

/**
 * PUT - Generate report data for client-side PDF generation
 *
 * Returns setup/product data with branding config for use with pdf-generator.js
 */
export async function PUT(request) {
  const session = await auth();

  if (!session?.user) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  // Check access
  const access = await checkUnifiedAccess({ userId: session.user.id });
  const limits = getPlanLimits(access.plan);

  if (!limits.whiteLabel) {
    return NextResponse.json(
      { error: "White-label reports require Enterprise plan", upgrade: true },
      { status: 403 }
    );
  }

  if (!isSupabaseConfigured()) {
    return NextResponse.json({ error: "Service unavailable" }, { status: 503 });
  }

  try {
    const { type, setupId, productSlugs, includeIncidents = true } = await request.json();

    // Get user's branding config
    const { data: brandingData } = await supabase
      .from("user_branding")
      .select("*")
      .eq("user_id", session.user.id)
      .single();

    const branding = brandingData ? {
      companyName: brandingData.company_name,
      logoBase64: brandingData.logo_base64 || null,
      primaryColor: brandingData.primary_color || DEFAULT_BRANDING.primaryColor,
      secondaryColor: brandingData.secondary_color || DEFAULT_BRANDING.secondaryColor,
      headerColor: brandingData.header_color || "#1F2937",
      footerText: brandingData.footer_text || DEFAULT_BRANDING.footerText,
      websiteUrl: brandingData.website_url || "",
      reportTitle: brandingData.header_text || DEFAULT_BRANDING.headerText,
      hideSafeScoring: brandingData.show_safescoring === false,
    } : DEFAULT_BRANDING;

    let reportData = { branding };

    if (type === "setup" && setupId) {
      // Get setup with products
      const { data: setup, error } = await supabase
        .from("user_setups")
        .select("*")
        .eq("id", setupId)
        .eq("user_id", session.user.id)
        .single();

      if (error || !setup) {
        return NextResponse.json({ error: "Setup not found" }, { status: 404 });
      }

      // Get product details
      const productSlugsFromSetup = setup.products?.map(p => p.slug || p.productSlug) || [];
      let productDetails = [];
      let incidents = [];

      if (productSlugsFromSetup.length > 0) {
        const { data: products } = await supabase
          .from("products")
          .select(`
            id, name, slug, type_name, category,
            safe_scoring_results (note_finale, score_s, score_a, score_f, score_e)
          `)
          .in("slug", productSlugsFromSetup);

        productDetails = (products || []).map(p => {
          const setupProduct = setup.products.find(sp => sp.slug === p.slug || sp.productSlug === p.slug);
          return {
            name: p.name,
            slug: p.slug,
            type_name: p.type_name,
            category: p.category,
            role: setupProduct?.role || "other",
            scores: {
              note_finale: p.safe_scoring_results?.note_finale,
              score_s: p.safe_scoring_results?.score_s,
              score_a: p.safe_scoring_results?.score_a,
              score_f: p.safe_scoring_results?.score_f,
              score_e: p.safe_scoring_results?.score_e,
            },
          };
        });

        // Get incidents if requested
        if (includeIncidents) {
          const productIds = products?.map(p => p.id).filter(Boolean) || [];
          if (productIds.length > 0) {
            const { data: incidentData } = await supabase
              .from("security_incidents")
              .select("id, title, date, severity, product_id, source_url")
              .in("product_id", productIds)
              .order("date", { ascending: false })
              .limit(10);

            incidents = (incidentData || []).map(inc => ({
              ...inc,
              product_name: productDetails.find(p => p.id === inc.product_id)?.name,
            }));
          }
        }
      }

      reportData = {
        ...reportData,
        type: "setup",
        setup: {
          name: setup.name,
          combinedScore: setup.combined_score || {
            note_finale: setup.score,
            score_s: setup.pillar_scores?.s,
            score_a: setup.pillar_scores?.a,
            score_f: setup.pillar_scores?.f,
            score_e: setup.pillar_scores?.e,
          },
          productDetails,
        },
        incidents,
        weaknesses: setup.weaknesses || [],
      };

    } else if (type === "comparison" && productSlugs?.length > 0) {
      // Get products for comparison
      const { data: products } = await supabase
        .from("products")
        .select(`
          id, name, slug, type_name, category,
          safe_scoring_results (note_finale, score_s, score_a, score_f, score_e)
        `)
        .in("slug", productSlugs);

      reportData = {
        ...reportData,
        type: "comparison",
        products: (products || []).map(p => ({
          name: p.name,
          slug: p.slug,
          type_name: p.type_name,
          category: p.category,
          score: p.safe_scoring_results?.note_finale,
          scores: {
            note_finale: p.safe_scoring_results?.note_finale,
            score_s: p.safe_scoring_results?.score_s,
            score_a: p.safe_scoring_results?.score_a,
            score_f: p.safe_scoring_results?.score_f,
            score_e: p.safe_scoring_results?.score_e,
          },
        })),
      };

    } else if (type === "product" && productSlugs?.[0]) {
      // Single product report
      const { data: product, error } = await supabase
        .from("products")
        .select(`
          id, name, slug, type_name, category, description,
          safe_scoring_results (note_finale, score_s, score_a, score_f, score_e)
        `)
        .eq("slug", productSlugs[0])
        .single();

      if (error || !product) {
        return NextResponse.json({ error: "Product not found" }, { status: 404 });
      }

      let incidents = [];
      if (includeIncidents) {
        const { data: incidentData } = await supabase
          .from("security_incidents")
          .select("id, title, date, severity, source_url")
          .eq("product_id", product.id)
          .order("date", { ascending: false })
          .limit(5);

        incidents = incidentData || [];
      }

      reportData = {
        ...reportData,
        type: "product",
        product: {
          name: product.name,
          slug: product.slug,
          type_name: product.type_name,
          category: product.category,
          description: product.description,
          score: product.safe_scoring_results?.note_finale,
          scores: {
            note_finale: product.safe_scoring_results?.note_finale,
            score_s: product.safe_scoring_results?.score_s,
            score_a: product.safe_scoring_results?.score_a,
            score_f: product.safe_scoring_results?.score_f,
            score_e: product.safe_scoring_results?.score_e,
          },
        },
        incidents,
      };

    } else {
      return NextResponse.json(
        { error: "Invalid report type. Use 'setup', 'comparison', or 'product'" },
        { status: 400 }
      );
    }

    // Log report generation for analytics (silent fail)
    supabase.from("report_generations").insert({
      user_id: session.user.id,
      report_type: type,
      branding_used: !!brandingData?.company_name,
      created_at: new Date().toISOString(),
    }).then(() => {}).catch(() => {});

    return NextResponse.json({
      ...reportData,
      generatedAt: new Date().toISOString(),
      message: "Use this data with pdf-generator.js to create branded PDFs",
    });

  } catch (error) {
    console.error("Error in white-label PUT:", error);
    return NextResponse.json({ error: "Internal server error" }, { status: 500 });
  }
}

// Generate report HTML
function generateReportHtml(products, branding, includeDetails) {
  const date = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const avgScore = products.reduce((sum, p) =>
    sum + (p.safe_scoring_results?.note_finale || 0), 0) / products.length;

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>${branding.headerText}</title>
  <style>
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif;
      line-height: 1.6;
      color: #1f2937;
      padding: 40px;
      max-width: 900px;
      margin: 0 auto;
    }
    .header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      border-bottom: 3px solid ${branding.primaryColor};
      padding-bottom: 20px;
      margin-bottom: 30px;
    }
    .logo {
      font-size: 24px;
      font-weight: bold;
      color: ${branding.primaryColor};
    }
    .logo img {
      max-height: 50px;
    }
    .date {
      color: #6b7280;
      font-size: 14px;
    }
    h1 {
      color: ${branding.primaryColor};
      font-size: 28px;
      margin-bottom: 10px;
    }
    .summary {
      background: linear-gradient(135deg, ${branding.primaryColor}15, ${branding.secondaryColor}15);
      border-radius: 12px;
      padding: 24px;
      margin-bottom: 30px;
    }
    .summary-score {
      font-size: 48px;
      font-weight: bold;
      color: ${branding.primaryColor};
    }
    .summary-label {
      color: #6b7280;
      font-size: 14px;
    }
    .products {
      margin-top: 30px;
    }
    .product {
      border: 1px solid #e5e7eb;
      border-radius: 8px;
      padding: 20px;
      margin-bottom: 16px;
    }
    .product-header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      margin-bottom: 12px;
    }
    .product-name {
      font-size: 18px;
      font-weight: 600;
    }
    .product-score {
      font-size: 24px;
      font-weight: bold;
      color: ${branding.primaryColor};
    }
    .pillars {
      display: grid;
      grid-template-columns: repeat(4, 1fr);
      gap: 12px;
      margin-top: 12px;
    }
    .pillar {
      text-align: center;
      padding: 8px;
      background: #f9fafb;
      border-radius: 6px;
    }
    .pillar-name {
      font-size: 12px;
      color: #6b7280;
      text-transform: uppercase;
    }
    .pillar-score {
      font-size: 18px;
      font-weight: 600;
      color: ${branding.secondaryColor};
    }
    .footer {
      margin-top: 40px;
      padding-top: 20px;
      border-top: 1px solid #e5e7eb;
      text-align: center;
      color: #9ca3af;
      font-size: 12px;
    }
    .powered-by {
      margin-top: 8px;
      font-size: 10px;
    }
    ${branding.customCss || ""}
  </style>
</head>
<body>
  <div class="header">
    <div class="logo">
      ${branding.logoUrl
        ? `<img src="${branding.logoUrl}" alt="${branding.companyName}">`
        : branding.companyName
      }
    </div>
    <div class="date">${date}</div>
  </div>

  <h1>${branding.headerText}</h1>

  <div class="summary">
    <div class="summary-label">Overall Security Score</div>
    <div class="summary-score">${avgScore.toFixed(1)}</div>
    <div class="summary-label">${products.length} product${products.length > 1 ? "s" : ""} evaluated</div>
  </div>

  <div class="products">
    <h2>Product Evaluations</h2>
    ${products.map(p => `
      <div class="product">
        <div class="product-header">
          <span class="product-name">${p.name}</span>
          <span class="product-score">${(p.safe_scoring_results?.note_finale || 0).toFixed(1)}</span>
        </div>
        ${includeDetails ? `
          <div class="pillars">
            <div class="pillar">
              <div class="pillar-name">Security</div>
              <div class="pillar-score">${(p.safe_scoring_results?.score_s || 0).toFixed(0)}</div>
            </div>
            <div class="pillar">
              <div class="pillar-name">Adversity</div>
              <div class="pillar-score">${(p.safe_scoring_results?.score_a || 0).toFixed(0)}</div>
            </div>
            <div class="pillar">
              <div class="pillar-name">Fidelity</div>
              <div class="pillar-score">${(p.safe_scoring_results?.score_f || 0).toFixed(0)}</div>
            </div>
            <div class="pillar">
              <div class="pillar-name">Efficiency</div>
              <div class="pillar-score">${(p.safe_scoring_results?.score_e || 0).toFixed(0)}</div>
            </div>
          </div>
        ` : ""}
      </div>
    `).join("")}
  </div>

  <div class="footer">
    <div>${branding.footerText}</div>
    ${branding.showSafeScoring ? `
      <div class="powered-by">Powered by SafeScoring.io - Cryptocurrency Security Intelligence</div>
    ` : ""}
  </div>
</body>
</html>
  `.trim();
}
