#!/usr/bin/env python3
"""
Add contextual compatibility action steps (to-do list) for each type combination.
Generated by Claude Code Opus - 3 actionable phrases max per combination.
"""

import requests
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent / 'src'))
from core.config import CONFIG

TOKEN = 'sbp_e4b8b78cd32053ff0436cea95ec5adb21a9db936'
PROJECT_REF = 'ajdncttomdqojlozxjxu'

SUPABASE_URL = CONFIG.get('SUPABASE_URL', 'https://ajdncttomdqojlozxjxu.supabase.co')
SERVICE_ROLE_KEY = CONFIG.get('SUPABASE_SERVICE_ROLE_KEY', '')
HEADERS = {
    'apikey': SERVICE_ROLE_KEY,
    'Authorization': f'Bearer {SERVICE_ROLE_KEY}',
    'Content-Type': 'application/json',
}

# Contextual action steps by type combination
# Each entry: list of 1-3 actionable steps
COMPATIBILITY_STEPS = {
    # Hardware Wallet + Software Wallet combinations
    ('HW Cold', 'SW Browser'): [
        "Install the browser extension and connect your hardware wallet via USB or Bluetooth.",
        "Enable blind signing only if required by the dApp, and always verify on device.",
        "Bookmark trusted dApp URLs to avoid phishing when initiating transactions."
    ],
    ('HW Cold', 'SW Mobile'): [
        "Pair your hardware wallet with the mobile app via Bluetooth in a secure environment.",
        "Enable biometric lock on the mobile app for an additional security layer.",
        "Verify the receiving address on both the mobile screen and hardware display before confirming."
    ],
    ('HW Cold', 'SW Desktop'): [
        "Download the official desktop application from the manufacturer website only.",
        "Connect via USB and verify the device is recognized before initiating transfers.",
        "Keep both firmware and desktop software updated to the latest versions."
    ],

    # Hardware + DeFi
    ('HW Cold', 'DEX'): [
        "Connect through a trusted browser extension that supports hardware wallet signing.",
        "Review and limit token approval amounts before confirming on your device.",
        "Use a DEX aggregator to find optimal rates while maintaining hardware security."
    ],
    ('HW Cold', 'Lending'): [
        "Connect your hardware wallet to the lending protocol via browser extension.",
        "Set a health factor alert and monitor collateral ratios through a dashboard.",
        "Approve only the exact collateral amount needed, not unlimited approvals."
    ],
    ('HW Cold', 'Liq Staking'): [
        "Access the liquid staking protocol through your hardware-connected browser wallet.",
        "Confirm the staking contract address matches the official protocol documentation.",
        "Stake in smaller batches first to verify the flow before committing larger amounts."
    ],
    ('HW Cold', 'Bridges'): [
        "Verify the bridge contract address through multiple official sources before approving.",
        "Start with a small test transaction to confirm the bridge route works correctly.",
        "Monitor the bridging transaction status and keep the destination wallet ready."
    ],
    ('HW Cold', 'CEX'): [
        "Generate a deposit address on the exchange and whitelist it if the feature is available.",
        "Initiate the transfer from your hardware wallet, verifying the address on device.",
        "Wait for sufficient network confirmations before trading the deposited funds."
    ],
    ('HW Cold', 'Card'): [
        "Generate a deposit address from your crypto card provider dashboard.",
        "Transfer only the amount you plan to spend from your hardware wallet.",
        "Set up transaction notifications on the card app to monitor spending in real-time."
    ],
    ('HW Cold', 'Yield'): [
        "Connect to the yield protocol through your hardware-enabled browser extension.",
        "Review the smart contract audit status before depositing any funds.",
        "Start with a test deposit to verify rewards accrual before larger commitments."
    ],

    # Software Wallet combinations
    ('SW Browser', 'SW Mobile'): [
        "Import your seed phrase into the mobile wallet in a private, offline environment.",
        "Enable different security settings (PIN/biometric) on each device for segmentation.",
        "Consider using the mobile wallet for daily transactions and browser for DeFi."
    ],
    ('SW Browser', 'DEX'): [
        "Connect your wallet to the DEX using the official connect button on the protocol site.",
        "Review token approvals before signing and use exact amounts when possible.",
        "Regularly check and revoke unused approvals via tools like Revoke.cash."
    ],
    ('SW Browser', 'Lending'): [
        "Connect your wallet and supply collateral through the protocol interface.",
        "Set up health factor monitoring alerts through the protocol or a third-party tool.",
        "Keep some assets liquid to top up collateral quickly if needed."
    ],
    ('SW Browser', 'CEX'): [
        "Copy the exchange deposit address carefully and verify the network type matches.",
        "Send a small test transaction first to confirm the address is correct.",
        "Enable withdrawal address whitelisting on the exchange for added security."
    ],
    ('SW Browser', 'Bridges'): [
        "Select the source and destination chains, then connect your wallet to the bridge.",
        "Approve the token spending and confirm the bridge transaction in your wallet.",
        "Monitor the transaction status and switch networks to claim on the destination chain."
    ],
    ('SW Mobile', 'DEX'): [
        "Scan the WalletConnect QR code displayed on the DEX website with your mobile wallet.",
        "Review all transaction details in the mobile app before approving.",
        "Disconnect the session after completing your swaps to prevent unauthorized access."
    ],
    ('SW Mobile', 'Card'): [
        "Link your mobile wallet to the card provider through their official app.",
        "Set daily spending limits that match your typical usage patterns.",
        "Enable real-time push notifications to monitor all card transactions."
    ],
    ('SW Mobile', 'CEX'): [
        "Use the exchange mobile app to generate a deposit address with QR code.",
        "Scan the QR directly from your wallet app to avoid address copy errors.",
        "Verify the network and amount before confirming the transfer."
    ],

    # CEX combinations
    ('CEX', 'CEX'): [
        "Initiate a withdrawal from the source exchange to the destination exchange address.",
        "Double-check that both exchanges support the same network for the asset.",
        "Track the transaction hash and wait for confirmations before the funds appear."
    ],
    ('CEX', 'DEX'): [
        "Withdraw from the exchange to your self-custody wallet first.",
        "Connect your wallet to the DEX and execute your desired swap.",
        "Consider gas costs and timing when planning the withdrawal and swap sequence."
    ],
    ('CEX', 'Card'): [
        "If same provider, enable direct spending from your exchange balance.",
        "If different providers, transfer funds to the card wallet address first.",
        "Monitor both exchange and card balances to maintain spending availability."
    ],
    ('CEX', 'Lending'): [
        "Withdraw funds from the exchange to a self-custody wallet.",
        "Connect your wallet to the lending protocol and deposit as collateral.",
        "Keep withdrawal records for tax purposes and position tracking."
    ],
    ('CEX', 'Bridges'): [
        "Withdraw from the exchange to your wallet on the source chain.",
        "Connect to the bridge, approve tokens, and initiate the cross-chain transfer.",
        "Claim the bridged tokens on the destination chain once confirmed."
    ],

    # DeFi combinations
    ('DEX', 'DEX'): [
        "Use a DEX aggregator like 1inch or Paraswap to find the best route automatically.",
        "Compare gas costs and slippage across different DEX routes before executing.",
        "Split large trades across multiple DEXs to minimize price impact."
    ],
    ('DEX', 'Lending'): [
        "Swap tokens on the DEX first, then deposit the result as lending collateral.",
        "Monitor both DEX liquidity and lending health factor for your positions.",
        "Consider using a protocol that combines both features to reduce transaction steps."
    ],
    ('DEX', 'Yield'): [
        "Swap to the required LP token pair on the DEX before depositing in yield farms.",
        "Add liquidity to create LP tokens, then stake them in the yield protocol.",
        "Calculate impermanent loss risk alongside yield rewards before committing."
    ],
    ('DEX', 'Bridges'): [
        "Bridge your tokens to the destination chain first if liquidity is better there.",
        "Use cross-chain aggregators that combine bridging and swapping in one transaction.",
        "Compare native DEX liquidity on both chains before choosing your route."
    ],
    ('Lending', 'Lending'): [
        "Monitor health factors across all lending positions through a dashboard like DeBank.",
        "Avoid using borrowed funds as collateral on another protocol (recursive leverage).",
        "Set up alerts for both platforms to prevent cascading liquidations."
    ],
    ('Lending', 'Liq Staking'): [
        "Stake your ETH to receive LST tokens, then deposit them as lending collateral.",
        "Monitor the LST peg closely as depeg events can trigger liquidation.",
        "Use conservative loan-to-value ratios given the additional LST volatility risk."
    ],
    ('Lending', 'Yield'): [
        "Deposit collateral and borrow stablecoins, then deploy them in yield strategies.",
        "Ensure yield APY exceeds borrowing APR plus gas costs for profitability.",
        "Maintain a buffer for health factor fluctuations during high volatility."
    ],

    # Liquid Staking
    ('Liq Staking', 'Liq Staking'): [
        "Deposit LST into restaking protocols like EigenLayer for additional yield.",
        "Understand that restaking adds another layer of slashing risk.",
        "Monitor both the base staking protocol and restaking platform status."
    ],
    ('Liq Staking', 'DEX'): [
        "Check LST liquidity depth on the DEX before initiating large swaps.",
        "Consider using Curve or specialized LST pools for better rates.",
        "Be aware of slight depeg during high redemption periods."
    ],
    ('Liq Staking', 'Yield'): [
        "Deposit your LST tokens into yield aggregators that support them.",
        "Compare base staking yield plus additional yield against risks involved.",
        "Diversify across multiple yield sources to reduce protocol-specific risk."
    ],

    # Bridges
    ('Bridges', 'Bridges'): [
        "Map out the complete route before starting multi-hop bridge transactions.",
        "Use each bridge official interface and verify contract addresses.",
        "Account for total bridging time and gas costs across all hops."
    ],
    ('Bridges', 'Lending'): [
        "Bridge tokens to the target chain, then deposit into the lending protocol.",
        "Verify that bridged token versions are accepted as collateral.",
        "Check if native vs canonical token versions have different collateral factors."
    ],

    # Backup combinations
    ('Bkp Physical', 'HW Cold'): [
        "Generate your seed phrase on the hardware wallet in a secure environment.",
        "Engrave or stamp the seed onto the metal backup following the BIP39 format.",
        "Store the backup in a separate physical location from your hardware device."
    ],
    ('Bkp Physical', 'Bkp Physical'): [
        "Create identical copies of your seed phrase on multiple metal plates.",
        "Store each backup in a different geographic location for disaster protection.",
        "Consider using Shamir Secret Sharing to split the seed across locations."
    ],
    ('Bkp Digital', 'HW Cold'): [
        "Encrypt your seed phrase backup using strong encryption before storing digitally.",
        "Store the encrypted file offline on a USB drive, not cloud storage.",
        "Test the recovery process periodically to ensure the backup is valid."
    ],

    # Stablecoin combinations
    ('Stablecoin', 'Stablecoin'): [
        "Use DEX pools optimized for stablecoin swaps like Curve for minimal slippage.",
        "Diversify holdings across different stablecoin types (USDC, DAI, USDT).",
        "Monitor reserve audits and backing ratios for each stablecoin you hold."
    ],
    ('Stablecoin', 'DEX'): [
        "Provide liquidity to stablecoin pairs for lower impermanent loss risk.",
        "Use stablecoins as your base trading pair for predictable value.",
        "Check stablecoin oracle prices on DEXs match market rates."
    ],
    ('Stablecoin', 'Lending'): [
        "Deposit stablecoins as collateral for stable borrowing rates.",
        "Borrow against stablecoins for lower liquidation risk strategies.",
        "Compare lending rates across protocols to maximize yield."
    ],
    ('Stablecoin', 'Yield'): [
        "Deposit stablecoins in yield aggregators for relatively stable returns.",
        "Compare yield sources and understand where the yield comes from.",
        "Set realistic APY expectations, very high stable yields often carry hidden risks."
    ],

    # Card combinations
    ('Card', 'SW Mobile'): [
        "Link your mobile wallet address to the card provider for easy top-ups.",
        "Set up automatic top-ups or alerts when card balance runs low.",
        "Review spending limits and adjust based on your usage patterns."
    ],
    ('Card', 'CEX'): [
        "Connect your exchange account to the card provider if they offer integration.",
        "Otherwise, withdraw to the card wallet address before spending.",
        "Track crypto-to-fiat conversion rates applied to card transactions."
    ],

    # CeFi / Crypto Bank
    ('Crypto Bank', 'CEX'): [
        "Link your crypto bank account to the exchange for fiat on/off ramp.",
        "Verify both institutions are properly licensed in your jurisdiction.",
        "Use bank transfers for larger amounts to benefit from lower fees."
    ],
    ('Crypto Bank', 'Card'): [
        "Request a debit card linked to your crypto bank account if available.",
        "Set spending limits and enable notifications for all card transactions.",
        "Understand the auto-conversion rules for crypto-backed spending."
    ],
    ('CeFi Lending', 'CEX'): [
        "Transfer funds from exchange to CeFi lending platform to earn yield.",
        "Compare CeFi rates with DeFi alternatives and assess counterparty risk.",
        "Only deposit amounts you can afford to have locked during term periods."
    ],

    # Custody / MultiSig
    ('Custody', 'HW Cold'): [
        "Coordinate with your custodian to set up approved withdrawal addresses.",
        "Initiate withdrawal requests through the custodian portal.",
        "Receive funds to your hardware wallet after custodian approval."
    ],
    ('MultiSig', 'HW Cold'): [
        "Set up each signer with their own hardware wallet for maximum security.",
        "Configure the multisig threshold based on your security requirements.",
        "Test the signing flow with a small transaction before large transfers."
    ],
    ('MultiSig', 'DEX'): [
        "Connect the Safe or multisig wallet to the DEX interface.",
        "Create the transaction proposal and gather required signer approvals.",
        "Execute the transaction once the signature threshold is met."
    ],

    # MPC Wallet
    ('MPC Wallet', 'DEX'): [
        "Connect your MPC wallet to the DEX like any standard wallet.",
        "Approve transactions through your MPC provider authentication flow.",
        "The MPC computation happens seamlessly during the signing process."
    ],
    ('MPC Wallet', 'HW Cold'): [
        "Use MPC for frequent, smaller transactions requiring convenience.",
        "Keep larger holdings on hardware wallet for maximum security.",
        "Consider MPC as your hot wallet and hardware as your cold storage."
    ],

    # DEX Aggregator
    ('DEX Agg', 'DEX'): [
        "Use the aggregator interface to automatically find best DEX routes.",
        "Review the routing path shown before confirming the transaction.",
        "Check that approval amounts are set correctly for each DEX in the route."
    ],
    ('DEX Agg', 'SW Browser'): [
        "Connect your browser wallet to the aggregator site.",
        "Compare quotes across aggregators before executing large swaps.",
        "Use limit orders if the aggregator supports them for better execution."
    ],

    # Perps / Options
    ('Perps', 'SW Browser'): [
        "Connect your wallet and deposit collateral into the perpetuals protocol.",
        "Set stop-loss and take-profit orders before opening positions.",
        "Monitor funding rates and adjust position size accordingly."
    ],
    ('Options', 'SW Browser'): [
        "Connect to the options protocol and deposit collateral for writing options.",
        "Understand the expiry date and strike price before buying options.",
        "Start with small position sizes while learning options mechanics."
    ],

    # RWA
    ('RWA', 'Lending'): [
        "Verify the RWA token is whitelisted as collateral on the lending protocol.",
        "Understand the specific liquidation parameters for RWA collateral.",
        "Monitor both on-chain and off-chain factors affecting RWA value."
    ],
    ('RWA', 'DEX'): [
        "Check if the RWA token has sufficient DEX liquidity before trading.",
        "Be aware of potential transfer restrictions on certain RWA tokens.",
        "Verify the RWA token contract address through official issuer channels."
    ],

    # Fiat Gateway
    ('Fiat Gateway', 'SW Browser'): [
        "Connect your wallet to the fiat gateway and complete KYC verification.",
        "Select your payment method and enter the purchase amount.",
        "Confirm the transaction and receive tokens directly to your wallet."
    ],
    ('Fiat Gateway', 'SW Mobile'): [
        "Download the gateway app or use mobile browser to access the service.",
        "Complete identity verification using your phone camera for documents.",
        "Use Apple Pay or Google Pay for faster checkout if supported."
    ],
    ('Fiat Gateway', 'CEX'): [
        "Use the exchange built-in fiat gateway or link an external provider.",
        "Compare fees between different payment methods before purchasing.",
        "Enable instant buy features for quicker access to trading."
    ],

    # L2 combinations
    ('L2', 'DEX'): [
        "Bridge assets to the L2 network using the official bridge.",
        "Connect your wallet to the L2-native DEX and add the network to your wallet.",
        "Enjoy lower gas fees while maintaining similar DEX functionality."
    ],
    ('L2', 'Bridges'): [
        "Use the canonical L2 bridge for highest security when moving to L2.",
        "For faster exits, consider third-party bridges but verify their audit status.",
        "Plan for withdrawal delays when moving assets back to L1."
    ],
    ('L2', 'Lending'): [
        "Bridge collateral to L2 where lending gas costs are significantly lower.",
        "Connect to L2-native lending protocols through your wallet.",
        "Monitor positions more frequently since L2 transactions are cheap."
    ],
    ('L2', 'SW Browser'): [
        "Add the L2 network to your browser wallet using chain settings.",
        "Switch networks in your wallet when interacting with L2 dApps.",
        "Keep small amounts of ETH on L2 for gas fees."
    ],

    # Insurance
    ('Insurance', 'Lending'): [
        "Purchase coverage for your lending position from a DeFi insurance protocol.",
        "Select coverage amount and duration based on your position size.",
        "File claims promptly if a covered event occurs following protocol procedures."
    ],
    ('Insurance', 'DEX'): [
        "Check if your DEX or LP position is eligible for coverage.",
        "Compare premium costs against potential loss scenarios.",
        "Read the coverage terms carefully to understand exclusions."
    ],
}

def escape_sql(s):
    return s.replace("'", "''") if s else ''

def execute_sql(query):
    r = requests.post(
        f'https://api.supabase.com/v1/projects/{PROJECT_REF}/database/query',
        headers={'Authorization': f'Bearer {TOKEN}', 'Content-Type': 'application/json'},
        json={'query': query}
    )
    return r.status_code == 201, r.text

def get_steps(type_a, type_b):
    """Get action steps for type combination"""
    key1 = (type_a, type_b)
    key2 = (type_b, type_a)

    if key1 in COMPATIBILITY_STEPS:
        return COMPATIBILITY_STEPS[key1]
    if key2 in COMPATIBILITY_STEPS:
        return COMPATIBILITY_STEPS[key2]

    # Generate contextual default steps based on type characteristics
    hw_types = ['HW Cold', 'HW Wallet', 'Bkp Physical']
    sw_types = ['SW Browser', 'SW Mobile', 'SW Desktop']
    cex_types = ['CEX', 'Crypto Bank']
    defi_types = ['DEX', 'Lending', 'Yield', 'Liq Staking', 'Bridges']

    steps = []

    # Hardware involved
    if type_a in hw_types or type_b in hw_types:
        other = type_b if type_a in hw_types else type_a
        steps.append(f"Connect your hardware wallet to interact with {other} securely.")
        steps.append("Verify all transaction details on the hardware device screen before signing.")
        steps.append("Keep your firmware updated and store recovery phrase safely.")

    # Software wallet to DeFi
    elif (type_a in sw_types or type_b in sw_types) and (type_a in defi_types or type_b in defi_types):
        defi = type_a if type_a in defi_types else type_b
        steps.append(f"Connect your wallet to the {defi} protocol through the official interface.")
        steps.append("Review and approve token allowances with appropriate limits.")
        steps.append("Bookmark the official URL and verify before each session.")

    # CEX involved
    elif type_a in cex_types or type_b in cex_types:
        other = type_b if type_a in cex_types else type_a
        steps.append(f"Generate the appropriate deposit or withdrawal address for {other}.")
        steps.append("Verify the network type matches between both platforms.")
        steps.append("Wait for required confirmations before considering transfer complete.")

    # DeFi to DeFi
    elif type_a in defi_types and type_b in defi_types:
        steps.append(f"Connect your wallet to both {type_a} and {type_b} protocols.")
        steps.append("Review smart contract approvals and set appropriate limits.")
        steps.append("Monitor positions across both protocols using a portfolio tracker.")

    # Default generic steps
    else:
        steps.append(f"Connect {type_a} with {type_b} using the appropriate interface or bridge.")
        steps.append("Verify addresses and transaction details before confirming.")
        steps.append("Start with a small test transaction to confirm the flow works correctly.")

    return steps[:3]

def format_pg_array(steps):
    """Format Python list as PostgreSQL array literal"""
    escaped = [escape_sql(s) for s in steps]
    return "ARRAY['" + "','".join(escaped) + "']"

def main():
    print("\n" + "=" * 60)
    print("  ADDING COMPATIBILITY ACTION STEPS (TO-DO LIST)")
    print("=" * 60)

    # Get types
    r = requests.get(f'{SUPABASE_URL}/rest/v1/product_types?select=id,code', headers=HEADERS)
    types = r.json() if r.status_code == 200 else []
    types_by_id = {t['id']: t['code'] for t in types}
    print(f"\n📦 {len(types)} types loaded")

    # Update type_compatibility with batch SQL
    print("\n📝 Updating type_compatibility with action steps...")

    r = requests.get(f'{SUPABASE_URL}/rest/v1/type_compatibility?select=id,type_a_id,type_b_id', headers=HEADERS)
    type_compats = r.json() if r.status_code == 200 else []

    # Build case statements for batch update
    cases = []
    ids = []
    for tc in type_compats:
        type_a = types_by_id.get(tc['type_a_id'], '')
        type_b = types_by_id.get(tc['type_b_id'], '')
        steps = get_steps(type_a, type_b)
        cases.append(f"WHEN {tc['id']} THEN {format_pg_array(steps)}")
        ids.append(str(tc['id']))

    # Execute in chunks
    chunk_size = 100
    updated = 0
    for i in range(0, len(cases), chunk_size):
        chunk_cases = cases[i:i+chunk_size]
        chunk_ids = ids[i:i+chunk_size]
        sql = f"""
        UPDATE type_compatibility
        SET compatibility_steps = CASE id {' '.join(chunk_cases)} END
        WHERE id IN ({','.join(chunk_ids)})
        """
        ok, _ = execute_sql(sql)
        if ok:
            updated += len(chunk_cases)

    print(f"   ✅ {updated}/{len(type_compats)} type compatibilities updated")

    # Update product_compatibility
    print("\n📝 Updating product_compatibility with action steps...")

    r = requests.get(f'{SUPABASE_URL}/rest/v1/products?select=id,type_id&type_id=not.is.null', headers=HEADERS)
    products = {p['id']: p['type_id'] for p in r.json()} if r.status_code == 200 else {}
    print(f"   {len(products)} products loaded")

    offset = 0
    limit = 500
    total = 0

    while True:
        r = requests.get(
            f'{SUPABASE_URL}/rest/v1/product_compatibility?select=id,product_a_id,product_b_id&offset={offset}&limit={limit}',
            headers=HEADERS
        )
        compats = r.json() if r.status_code == 200 else []

        if not compats:
            break

        # Build batch update
        cases = []
        ids = []
        for pc in compats:
            type_a_id = products.get(pc['product_a_id'])
            type_b_id = products.get(pc['product_b_id'])

            if not type_a_id or not type_b_id:
                continue

            type_a = types_by_id.get(type_a_id, '')
            type_b = types_by_id.get(type_b_id, '')
            steps = get_steps(type_a, type_b)
            cases.append(f"WHEN {pc['id']} THEN {format_pg_array(steps)}")
            ids.append(str(pc['id']))

        if cases:
            sql = f"""
            UPDATE product_compatibility
            SET compatibility_steps = CASE id {' '.join(cases)} END
            WHERE id IN ({','.join(ids)})
            """
            ok, _ = execute_sql(sql)
            if ok:
                total += len(cases)

        offset += limit
        if offset % 2000 == 0:
            print(f"   Processed {offset}...")

    print(f"   ✅ {total} product compatibilities updated")

    print("\n" + "=" * 60)
    print("  ✅ COMPATIBILITY ACTION STEPS ADDED")
    print("=" * 60)

if __name__ == "__main__":
    main()
