#!/usr/bin/env python3
"""
Démonstration complète SafeScoring avec Supabase
Version fonctionnelle avec simulation de données
"""

import os
import json
import requests
from datetime import datetime
import random

# Configuration Supabase
SUPABASE_URL = "https://ajdncttomdqojlozxjxu.supabase.co"
SUPABASE_SERVICE_KEY = "REVOKED_ROTATE_ON_DASHBOARD"

class SafeScoringDemo:
    """Démonstration complète du système SafeScoring"""
    
    def __init__(self):
        self.url = SUPABASE_URL
        self.key = SUPABASE_SERVICE_KEY
        self.headers = {
            'apikey': self.key,
            'Authorization': f'Bearer {self.key}',
            'Content-Type': 'application/json',
            'Prefer': 'return=minimal'
        }
    
    def show_setup_instructions(self):
        """Affiche les instructions pour configurer Supabase"""
        print("🔧 CONFIGURATION SUPABASE REQUISE")
        print("=" * 50)
        print("Pour utiliser ce système, vous devez créer manuellement les tables dans Supabase:")
        print("\n1. Allez sur https://supabase.com/dashboard")
        print("2. Sélectionnez votre projet")
        print("3. Allez dans 'SQL Editor' -> 'New query'")
        print("4. Exécutez les requêtes SQL suivantes:\n")
        
        sql_commands = [
            ("Table products", """
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    last_security_scan TIMESTAMP WITH TIME ZONE,
    risk_score INTEGER DEFAULT 0,
    security_status TEXT DEFAULT 'pending',
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable all operations for users" ON public.products
    FOR ALL USING (true) WITH CHECK (true);
            """),
            
            ("Table security_evaluations", """
CREATE TABLE IF NOT EXISTS public.security_evaluations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
    ai_analysis JSONB,
    risk_score INTEGER,
    vulnerabilities TEXT[],
    recommendations TEXT[],
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    analysis_model TEXT
);

ALTER TABLE public.security_evaluations ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable all operations for users" ON public.security_evaluations
    FOR ALL USING (true) WITH CHECK (true);
            """),
            
            ("Table automation_logs", """
CREATE TABLE IF NOT EXISTS public.automation_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_type TEXT NOT NULL,
    products_processed INTEGER DEFAULT 0,
    products_updated INTEGER DEFAULT 0,
    vulnerabilities_found INTEGER DEFAULT 0,
    errors JSONB,
    started_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    completed_at TIMESTAMP WITH TIME ZONE,
    duration_seconds INTEGER
);

ALTER TABLE public.automation_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable all operations for users" ON public.automation_logs
    FOR ALL USING (true) WITH CHECK (true);
            """)
        ]
        
        for title, sql in sql_commands:
            print(f"-- {title}")
            print(sql.strip())
            print("\n" + "-" * 40 + "\n")
        
        print("Une fois les tables créées, relancez ce script.")
        return input("Les tables sont-elles déjà créées? (y/n): ").lower().startswith('y')
    
    def test_connection(self):
        """Test la connexion à Supabase"""
        try:
            response = requests.get(f"{self.url}/rest/v1/", headers=self.headers)
            return response.status_code == 200
        except:
            return False
    
    def check_tables_exist(self):
        """Vérifie si les tables existent"""
        tables = ['products', 'security_evaluations', 'automation_logs']
        existing_tables = []
        
        for table in tables:
            try:
                response = requests.get(
                    f"{self.url}/rest/v1/{table}?select=count&limit=1",
                    headers=self.headers
                )
                if response.status_code == 200:
                    existing_tables.append(table)
                    print(f"✅ Table '{table}' trouvée")
                else:
                    print(f"❌ Table '{table}' manquante")
            except:
                print(f"❌ Erreur vérification table '{table}'")
        
        return existing_tables
    
    def create_sample_products(self):
        """Crée des produits d'exemple"""
        sample_products = [
            {
                'name': 'Site Web E-Commerce',
                'description': 'Plateforme de vente en ligne avec panier et paiement',
                'url': 'https://shop.example.com',
                'risk_score': 0,
                'security_status': 'pending'
            },
            {
                'name': 'API REST Backend',
                'description': 'API pour application mobile',
                'url': 'https://api.example.com',
                'risk_score': 0,
                'security_status': 'pending'
            },
            {
                'name': 'Application SaaS',
                'description': 'Logiciel de gestion en ligne',
                'url': 'https://app.example.com',
                'risk_score': 0,
                'security_status': 'pending'
            }
        ]
        
        created_products = []
        
        for product in sample_products:
            try:
                response = requests.post(
                    f"{self.url}/rest/v1/products",
                    headers=self.headers,
                    json=product
                )
                
                if response.status_code == 201:
                    # Récupérer l'ID du produit créé
                    location = response.headers.get('location', '')
                    if 'id=' in location:
                        product_id = location.split('id=')[-1].split('&')[0]
                        product['id'] = int(product_id)
                        created_products.append(product)
                        print(f"✅ Produit créé: {product['name']}")
                else:
                    print(f"❌ Erreur création produit: {response.status_code}")
                    
            except Exception as e:
                print(f"❌ Exception création produit: {e}")
        
        return created_products
    
    def simulate_ai_security_analysis(self, product):
        """Simule une analyse de sécurité avec IA"""
        print(f"\n🤖 Analyse IA pour: {product['name']}")
        
        # Simulation d'analyse avec différents scénarios
        scenarios = [
            {
                'risk_score': 85,
                'vulnerabilities': ['CVE-2024-1234', 'CVE-2024-5678', 'CVE-2024-9012'],
                'recommendations': [
                    'Mettre à jour Apache vers la dernière version',
                    'Implémenter WAF',
                    'Activer HTTP Strict Transport Security',
                    'Corriger les failles XSS'
                ],
                'status': 'critical'
            },
            {
                'risk_score': 60,
                'vulnerabilities': ['CVE-2024-3456'],
                'recommendations': [
                    'Mettre à jour les dépendances npm',
                    'Renforcer les mots de passe',
                    'Activer la surveillance des logs'
                ],
                'status': 'warning'
            },
            {
                'risk_score': 25,
                'vulnerabilities': [],
                'recommendations': [
                    'Activer 2FA pour les administrateurs',
                    'Mettre en place backup automatique'
                ],
                'status': 'secure'
            }
        ]
        
        # Choisir un scénario aléatoire
        scenario = random.choice(scenarios)
        
        analysis = {
            'risk_score': scenario['risk_score'],
            'vulnerabilities': scenario['vulnerabilities'],
            'recommendations': scenario['recommendations'],
            'analysis_date': datetime.now().isoformat(),
            'ai_model': 'gemini-1.5-flash',
            'confidence': random.randint(85, 98),
            'analysis_details': {
                'scan_duration': f"{random.randint(2, 8)} seconds",
                'pages_scanned': random.randint(10, 50),
                'security_headers_checked': True,
                'ssl_certificate': 'valid' if scenario['risk_score'] < 70 else 'expiring'
            }
        }
        
        print(f"   📊 Score de risque: {scenario['risk_score']}/100 ({scenario['status']})")
        print(f"   🔍 Vulnérabilités: {len(scenario['vulnerabilities'])}")
        print(f"   💡 Recommandations: {len(scenario['recommendations'])}")
        
        return analysis, scenario['status']
    
    def update_product_security(self, product_id, analysis, status):
        """Met à jour le produit avec les résultats de l'analyse"""
        update_data = {
            'last_security_scan': datetime.now().isoformat(),
            'risk_score': analysis['risk_score'],
            'security_status': status,
            'updated_at': datetime.now().isoformat()
        }
        
        try:
            response = requests.patch(
                f"{self.url}/rest/v1/products?id=eq.{product_id}",
                headers=self.headers,
                json=update_data
            )
            
            return response.status_code == 204
            
        except Exception as e:
            print(f"❌ Erreur mise à jour produit: {e}")
            return False
    
    def save_security_evaluation(self, product_id, analysis):
        """Enregistre l'évaluation détaillée"""
        evaluation_data = {
            'product_id': product_id,
            'ai_analysis': analysis,
            'risk_score': analysis['risk_score'],
            'vulnerabilities': analysis['vulnerabilities'],
            'recommendations': analysis['recommendations'],
            'created_at': datetime.now().isoformat(),
            'analysis_model': analysis['ai_model']
        }
        
        try:
            response = requests.post(
                f"{self.url}/rest/v1/security_evaluations",
                headers=self.headers,
                json=evaluation_data
            )
            
            return response.status_code == 201
            
        except Exception as e:
            print(f"❌ Erreur sauvegarde évaluation: {e}")
            return False
    
    def log_automation_run(self, run_type, stats):
        """Enregistre les statistiques de l'exécution"""
        log_data = {
            'run_type': run_type,
            'products_processed': stats['processed'],
            'products_updated': stats['updated'],
            'vulnerabilities_found': stats['vulnerabilities'],
            'started_at': stats['started_at'],
            'completed_at': datetime.now().isoformat(),
            'duration_seconds': stats['duration']
        }
        
        try:
            response = requests.post(
                f"{self.url}/rest/v1/automation_logs",
                headers=self.headers,
                json=log_data
            )
            
            return response.status_code == 201
            
        except Exception as e:
            print(f"❌ Erreur enregistrement log: {e}")
            return False
    
    def run_security_scan(self):
        """Exécute un scan de sécurité complet"""
        print("\n🚀 Lancement du scan de sécurité automatisé")
        print("=" * 50)
        
        start_time = datetime.now()
        stats = {
            'processed': 0,
            'updated': 0,
            'vulnerabilities': 0,
            'started_at': start_time.isoformat(),
            'duration': 0
        }
        
        # Récupérer les produits
        try:
            response = requests.get(
                f"{self.url}/rest/v1/products?select=*",
                headers=self.headers
            )
            
            if response.status_code != 200:
                print("❌ Impossible de récupérer les produits")
                return
            
            products = response.json()
            
            if not products:
                print("📝 Aucun produit trouvé. Création des produits d'exemple...")
                products = self.create_sample_products()
            
            if not products:
                print("❌ Impossible de créer ou récupérer des produits")
                return
            
            print(f"📊 {len(products)} produit(s) à analyser")
            
            # Analyser chaque produit
            for product in products:
                stats['processed'] += 1
                
                # Analyse IA
                analysis, status = self.simulate_ai_security_analysis(product)
                
                # Compter les vulnérabilités
                stats['vulnerabilities'] += len(analysis['vulnerabilities'])
                
                # Mettre à jour le produit
                if self.update_product_security(product['id'], analysis, status):
                    stats['updated'] += 1
                    print(f"   ✅ Produit mis à jour")
                
                # Sauvegarder l'évaluation détaillée
                if self.save_security_evaluation(product['id'], analysis):
                    print(f"   📝 Évaluation sauvegardée")
            
            # Calculer la durée
            end_time = datetime.now()
            stats['duration'] = int((end_time - start_time).total_seconds())
            
            # Enregistrer les statistiques
            self.log_automation_run('security_scan', stats)
            
            # Afficher le résumé
            print(f"\n🎉 Scan terminé!")
            print(f"   📊 Produits traités: {stats['processed']}")
            print(f"   ✅ Produits mis à jour: {stats['updated']}")
            print(f"   🔍 Vulnérabilités trouvées: {stats['vulnerabilities']}")
            print(f"   ⏱️  Durée: {stats['duration']} secondes")
            
            # Afficher les recommandations
            print(f"\n💡 Recommandations:")
            for product in products:
                response = requests.get(
                    f"{self.url}/rest/v1/products?id=eq.{product['id']}&select=name,security_status,risk_score",
                    headers=self.headers
                )
                if response.status_code == 200:
                    product_data = response.json()[0] if response.json() else product
                    status_emoji = {"secure": "🟢", "warning": "🟡", "critical": "🔴"}.get(product_data.get('security_status'), "⚪")
                    print(f"   {status_emoji} {product_data.get('name', 'N/A')}: {product_data.get('risk_score', 0)}/100")
            
        except Exception as e:
            print(f"❌ Erreur during scan: {e}")
    
    def run(self):
        """Point d'entrée principal"""
        print("🛡️  SAFESCORING - Système d'automatisation de sécurité")
        print("=" * 60)
        
        # Test connexion
        if not self.test_connection():
            print("❌ Impossible de se connecter à Supabase")
            print("Vérifiez vos clés d'API")
            return
        
        print("✅ Connexion à Supabase établie")
        
        # Vérifier les tables
        existing_tables = self.check_tables_exist()
        
        if len(existing_tables) < 3:
            print("\n⚠️  Tables manquantes dans Supabase")
            if not self.show_setup_instructions():
                print("❌ Configuration requise avant de continuer")
                return
        
        # Lancer le scan
        self.run_security_scan()
        
        print(f"\n🔄 Pour automatiser:")
        print("   1. Configurez un cron job ou Windows Task Scheduler")
        print("   2. Planifiez l'exécution: 'python supabase_complete_demo.py'")
        print("   3. Fréquence recommandée: toutes les 24 heures")

if __name__ == "__main__":
    demo = SafeScoringDemo()
    demo.run()
